DEF_LAUNCH_PARAM(logDXCalls, 0, "Logs all calls to DXCall")
DEF_LAUNCH_PARAM(logAllDXCalls, 0, "Logs all DX calls")
DEF_LAUNCH_PARAM(logDXNamedObjects, 0, "Logs all calls to when a DirectX object get a name.")
DEF_LAUNCH_PARAM(logShaderDebug, 0, "Logs extra info when compiling shader sources.")
DEF_LAUNCH_PARAM(logResources, 0, "Logs info about the GPU resources.")
DEF_LAUNCH_PARAM(injectRenderDoc, 0, "Enable RenderDoc to inject automatically into the process at startup.")
DEF_LAUNCH_PARAM(noSound, 0, "Disable all types of sounds.")