RS_DX12_HRESULT(DXGI_ERROR_ACCESS_DENIED, "You tried to use a resource to which you did not have the required access privileges. This error is most typically caused when you write to a shared resource with read-only access.")
RS_DX12_HRESULT(DXGI_ERROR_ACCESS_LOST, "The desktop duplication interface is invalid. The desktop duplication interface typically becomes invalid when a different type of image is displayed on the desktop.")
RS_DX12_HRESULT(DXGI_ERROR_ALREADY_EXISTS, "The desired element already exists. This is returned by DXGIDeclareAdapterRemovalSupport if it is not the first time that the function is called.")
RS_DX12_HRESULT(DXGI_ERROR_CANNOT_PROTECT_CONTENT, "DXGI can't provide content protection on the swap chain. This error is typically caused by an older driver, or when you use a swap chain that is incompatible with content protection.")
RS_DX12_HRESULT(DXGI_ERROR_DEVICE_HUNG, "The application's device failed due to badly formed commands sent by the application. This is an design-time issue that should be investigated and fixed.")
RS_DX12_HRESULT(DXGI_ERROR_DEVICE_REMOVED, "The video card has been physically removed from the system, or a driver upgrade for the video card has occurred. The application should destroy and recreate the device. For help debugging the problem, call ID3D10Device::GetDeviceRemovedReason.")
RS_DX12_HRESULT(DXGI_ERROR_DEVICE_RESET, "The device failed due to a badly formed command. This is a run-time issue; The application should destroy and recreate the device.")
RS_DX12_HRESULT(DXGI_ERROR_DRIVER_INTERNAL_ERROR, "The driver encountered a problem and was put into the device removed state.")
RS_DX12_HRESULT(DXGI_ERROR_FRAME_STATISTICS_DISJOINT, "An event (for example, a power cycle) interrupted the gathering of presentation statistics.")
RS_DX12_HRESULT(DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE, "The application attempted to acquire exclusive ownership of an output, but failed because some other application (or device within the application) already acquired ownership.")
RS_DX12_HRESULT(DXGI_ERROR_INVALID_CALL, "The application provided invalid parameter data; this must be debugged and fixed before the application is released.")
RS_DX12_HRESULT(DXGI_ERROR_MORE_DATA, "The buffer supplied by the application is not big enough to hold the requested data.")
RS_DX12_HRESULT(DXGI_ERROR_NAME_ALREADY_EXISTS, "The supplied name of a resource in a call to IDXGIResource1::CreateSharedHandle is already associated with some other resource.")
RS_DX12_HRESULT(DXGI_ERROR_NONEXCLUSIVE, "A global counter resource is in use, and the Direct3D device can't currently use the counter resource.")
RS_DX12_HRESULT(DXGI_ERROR_NOT_CURRENTLY_AVAILABLE, "The resource or request is not currently available, but it might become available later.")
RS_DX12_HRESULT(DXGI_ERROR_NOT_FOUND, "When calling IDXGIObject::GetPrivateData, the GUID passed in is not recognized as one previously passed to IDXGIObject::SetPrivateData or IDXGIObject::SetPrivateDataInterface. When calling IDXGIFactory::EnumAdapters or IDXGIAdapter::EnumOutputs, the enumerated ordinal is out of range.")
RS_DX12_HRESULT(DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED, "Reserved")
RS_DX12_HRESULT(DXGI_ERROR_REMOTE_OUTOFMEMORY, "Reserved")
RS_DX12_HRESULT(DXGI_ERROR_RESTRICT_TO_OUTPUT_STALE, "The DXGI output (monitor) to which the swap chain content was restricted is now disconnected or changed.")
RS_DX12_HRESULT(DXGI_ERROR_SDK_COMPONENT_MISSING, "The operation depends on an SDK component that is missing or mismatched.")
RS_DX12_HRESULT(DXGI_ERROR_SESSION_DISCONNECTED, "The Remote Desktop Services session is currently disconnected.")
RS_DX12_HRESULT(DXGI_ERROR_UNSUPPORTED, "The requested functionality is not supported by the device or the driver.")
RS_DX12_HRESULT(DXGI_ERROR_WAIT_TIMEOUT, "The time-out interval elapsed before the next desktop frame was available.")
RS_DX12_HRESULT(DXGI_ERROR_WAS_STILL_DRAWING, "The GPU was busy at the moment when a call was made to perform an operation, and did not execute or schedule the operation.")
RS_DX12_HRESULT(D3D12_ERROR_ADAPTER_NOT_FOUND, "The specified cached PSO was created on a different adapter and cannot be reused on the current adapter.")
RS_DX12_HRESULT(D3D12_ERROR_DRIVER_VERSION_MISMATCH, "The specified cached PSO was created on a different driver version and cannot be reused on the current adapter.")
RS_DX12_HRESULT(E_INVALIDARG, "An invalid parameter was passed to the returning function.")
RS_DX12_HRESULT(E_OUTOFMEMORY, "Direct3D could not allocate sufficient memory to complete the call.")
RS_DX12_HRESULT(E_NOTIMPL, "The method call isn't implemented with the passed parameter combination.")
RS_DX12_HRESULT(E_FAIL, "Attempted to create a device with the debug layer enabled and the layer is not installed.")
RS_DX12_HRESULT(S_FALSE, "Alternate success value, indicating a successful but nonstandard completion (the precise meaning depends on context).")
RS_DX12_HRESULT(S_OK, "	The method succeeded without an error.")