#include "PreCompiled.h"
#include "DXFormat.h"

RS::Format RS::ToDXFormat(DXGI_FORMAT format)
{
#define NOT_SUPPORTED RS_ASSERT(false, "DXGI_FORMAT {}, not supported!"); return Format::UNKNOWN

    switch (format)
    {
    case DXGI_FORMAT_R32G32B32A32_TYPELESS: return Format::RGBA32_TYPELESS;
    case DXGI_FORMAT_R32G32B32A32_FLOAT: return Format::RGBA32_FLOAT;
    case DXGI_FORMAT_R32G32B32A32_UINT: return Format::RGBA32_UINT;
    case DXGI_FORMAT_R32G32B32A32_SINT: return Format::RGBA32_SINT;
    case DXGI_FORMAT_R32G32B32_TYPELESS: return Format::RGB32_TYPELESS;
    case DXGI_FORMAT_R32G32B32_FLOAT: return Format::RGB32_FLOAT;
    case DXGI_FORMAT_R32G32B32_UINT: return Format::RGB32_UINT;
    case DXGI_FORMAT_R32G32B32_SINT: return Format::RGB32_SINT;
    case DXGI_FORMAT_R16G16B16A16_TYPELESS: return Format::RGBA16_TYPELESS;
    case DXGI_FORMAT_R16G16B16A16_FLOAT: return Format::RGBA16_FLOAT;
    case DXGI_FORMAT_R16G16B16A16_UNORM: return Format::RGBA16_UNORM;
    case DXGI_FORMAT_R16G16B16A16_UINT: return Format::RGBA16_UINT;
    case DXGI_FORMAT_R16G16B16A16_SNORM: return Format::RGBA16_SNORM;
    case DXGI_FORMAT_R16G16B16A16_SINT: return Format::RGBA16_SINT;
    case DXGI_FORMAT_R32G32_TYPELESS: return Format::RG32_TYPELESS;
    case DXGI_FORMAT_R32G32_FLOAT: return Format::RG32_FLOAT;
    case DXGI_FORMAT_R32G32_UINT: return Format::RG32_UINT;
    case DXGI_FORMAT_R32G32_SINT: return Format::RG32_SINT;
    case DXGI_FORMAT_R32G8X24_TYPELESS: NOT_SUPPORTED;
    case DXGI_FORMAT_D32_FLOAT_S8X24_UINT: NOT_SUPPORTED;
    case DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS: NOT_SUPPORTED;
    case DXGI_FORMAT_X32_TYPELESS_G8X24_UINT: NOT_SUPPORTED;
    case DXGI_FORMAT_R10G10B10A2_TYPELESS: return Format::RGB10A2_TYPELESS;
    case DXGI_FORMAT_R10G10B10A2_UNORM: return Format::RGB10A2_UNORM;
    case DXGI_FORMAT_R10G10B10A2_UINT: return Format::RGB10A2_UINT;
    case DXGI_FORMAT_R11G11B10_FLOAT: return Format::RG11B10_FLOAT;
    case DXGI_FORMAT_R8G8B8A8_TYPELESS: return Format::RGBA8_TYPELESS;
    case DXGI_FORMAT_R8G8B8A8_UNORM: return Format::RGBA8_UNORM;
    case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB: return Format::RGBA8_UNORM_SRGB;
    case DXGI_FORMAT_R8G8B8A8_UINT: return Format::RGBA8_UINT;
    case DXGI_FORMAT_R8G8B8A8_SNORM: return Format::RGBA8_SNORM;
    case DXGI_FORMAT_R8G8B8A8_SINT: return Format::RGBA8_SINT;
    case DXGI_FORMAT_R16G16_TYPELESS: return Format::RG16_TYPELESS;
    case DXGI_FORMAT_R16G16_FLOAT: return Format::RG16_FLOAT;
    case DXGI_FORMAT_R16G16_UNORM: return Format::RG16_UNORM;
    case DXGI_FORMAT_R16G16_UINT: return Format::RG16_UINT;
    case DXGI_FORMAT_R16G16_SNORM: return Format::RG16_SNORM;
    case DXGI_FORMAT_R16G16_SINT: return Format::RG16_SINT;
    case DXGI_FORMAT_R32_TYPELESS: return Format::R32_TYPELESS;
    case DXGI_FORMAT_D32_FLOAT: return Format::D32_FLOAT;
    case DXGI_FORMAT_R32_FLOAT: return Format::R32_FLOAT;
    case DXGI_FORMAT_R32_UINT: return Format::R32_UINT;
    case DXGI_FORMAT_R32_SINT: return Format::R32_SINT;
    case DXGI_FORMAT_R24G8_TYPELESS: NOT_SUPPORTED;
    case DXGI_FORMAT_D24_UNORM_S8_UINT: return Format::D32_UNORM_S8_UINT;
    case DXGI_FORMAT_R24_UNORM_X8_TYPELESS: NOT_SUPPORTED;
    case DXGI_FORMAT_X24_TYPELESS_G8_UINT: NOT_SUPPORTED;
    case DXGI_FORMAT_R8G8_TYPELESS: return Format::RG8_TYPELESS;
    case DXGI_FORMAT_R8G8_UNORM: return Format::RG8_UNORM;
    case DXGI_FORMAT_R8G8_UINT: return Format::RG8_UINT;
    case DXGI_FORMAT_R8G8_SNORM: return Format::RG8_SNORM;
    case DXGI_FORMAT_R8G8_SINT: return Format::RG8_SINT;
    case DXGI_FORMAT_R16_TYPELESS: return Format::R16_TYPELESS;
    case DXGI_FORMAT_R16_FLOAT: return Format::R16_FLOAT;
    case DXGI_FORMAT_D16_UNORM: return Format::D16_UNORM;
    case DXGI_FORMAT_R16_UNORM: return Format::R16_UNORM;
    case DXGI_FORMAT_R16_UINT: return Format::R16_UINT;
    case DXGI_FORMAT_R16_SNORM: return Format::R16_SNORM;
    case DXGI_FORMAT_R16_SINT: return Format::R16_SINT;
    case DXGI_FORMAT_R8_TYPELESS: return Format::R8_TYPELESS;
    case DXGI_FORMAT_R8_UNORM: return Format::R8_UNORM;
    case DXGI_FORMAT_R8_UINT: return Format::R8_UINT;
    case DXGI_FORMAT_R8_SNORM: return Format::R8_SNORM;
    case DXGI_FORMAT_R8_SINT: return Format::R8_SINT;
    case DXGI_FORMAT_A8_UNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_R1_UNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_R9G9B9E5_SHAREDEXP: NOT_SUPPORTED;
    case DXGI_FORMAT_R8G8_B8G8_UNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_G8R8_G8B8_UNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_BC1_TYPELESS: NOT_SUPPORTED;
    case DXGI_FORMAT_BC1_UNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_BC1_UNORM_SRGB: NOT_SUPPORTED;
    case DXGI_FORMAT_BC2_TYPELESS: NOT_SUPPORTED;
    case DXGI_FORMAT_BC2_UNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_BC2_UNORM_SRGB: NOT_SUPPORTED;
    case DXGI_FORMAT_BC3_TYPELESS: NOT_SUPPORTED;
    case DXGI_FORMAT_BC3_UNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_BC3_UNORM_SRGB: NOT_SUPPORTED;
    case DXGI_FORMAT_BC4_TYPELESS: NOT_SUPPORTED;
    case DXGI_FORMAT_BC4_UNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_BC4_SNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_BC5_TYPELESS: NOT_SUPPORTED;
    case DXGI_FORMAT_BC5_UNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_BC5_SNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_B5G6R5_UNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_B5G5R5A1_UNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_B8G8R8A8_UNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_B8G8R8X8_UNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_B8G8R8A8_TYPELESS: NOT_SUPPORTED;
    case DXGI_FORMAT_B8G8R8A8_UNORM_SRGB: NOT_SUPPORTED;
    case DXGI_FORMAT_B8G8R8X8_TYPELESS: NOT_SUPPORTED;
    case DXGI_FORMAT_B8G8R8X8_UNORM_SRGB: NOT_SUPPORTED;
    case DXGI_FORMAT_BC6H_TYPELESS: NOT_SUPPORTED;
    case DXGI_FORMAT_BC6H_UF16: NOT_SUPPORTED;
    case DXGI_FORMAT_BC6H_SF16: NOT_SUPPORTED;
    case DXGI_FORMAT_BC7_TYPELESS: NOT_SUPPORTED;
    case DXGI_FORMAT_BC7_UNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_BC7_UNORM_SRGB: NOT_SUPPORTED;
    case DXGI_FORMAT_AYUV: NOT_SUPPORTED;
    case DXGI_FORMAT_Y410: NOT_SUPPORTED;
    case DXGI_FORMAT_Y416: NOT_SUPPORTED;
    case DXGI_FORMAT_NV12: NOT_SUPPORTED;
    case DXGI_FORMAT_P010: NOT_SUPPORTED;
    case DXGI_FORMAT_P016: NOT_SUPPORTED;
    case DXGI_FORMAT_420_OPAQUE: NOT_SUPPORTED;
    case DXGI_FORMAT_YUY2: NOT_SUPPORTED;
    case DXGI_FORMAT_Y210: NOT_SUPPORTED;
    case DXGI_FORMAT_Y216: NOT_SUPPORTED;
    case DXGI_FORMAT_NV11: NOT_SUPPORTED;
    case DXGI_FORMAT_AI44: NOT_SUPPORTED;
    case DXGI_FORMAT_IA44: NOT_SUPPORTED;
    case DXGI_FORMAT_P8: NOT_SUPPORTED;
    case DXGI_FORMAT_A8P8: NOT_SUPPORTED;
    case DXGI_FORMAT_B4G4R4A4_UNORM: NOT_SUPPORTED;
    case DXGI_FORMAT_P208: NOT_SUPPORTED;
    case DXGI_FORMAT_V208: NOT_SUPPORTED;
    case DXGI_FORMAT_V408: NOT_SUPPORTED;
    case DXGI_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE: NOT_SUPPORTED;
    case DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE: NOT_SUPPORTED;
    case DXGI_FORMAT_FORCE_UINT: NOT_SUPPORTED;
    case DXGI_FORMAT_UNKNOWN:
    default:
        return Format::UNKNOWN;
    }

#undef NOT_SUPPORTED
    return Format::UNKNOWN;
}
